import SwiftUI

enum AppLanguage: String, CaseIterable { case de, en }
final class LanguageSettings: ObservableObject {
    static let shared=LanguageSettings()
    @Published var language: AppLanguage { didSet { defaults?.set(language.rawValue,forKey:"interfaceLanguage") } }
    private let defaults: UserDefaults?
    init(defaults: UserDefaults? = .standard) {
        #if MEDIA_EXPORT
        self.defaults=nil;language = .en
        #else
        self.defaults=defaults
        language=AppLanguage(rawValue:defaults?.string(forKey:"interfaceLanguage") ?? "") ?? (Locale.preferredLanguages.first?.hasPrefix("de") == true ? .de:.en)
        #endif
    }
}
func tr(_ value:String) -> String { LocalizedCopy.translate(value,to:LanguageSettings.shared.language) }
enum LocalizedCopy {
    static let english: [String:String] = [
        "VERBINDET …": "CONNECTING …",
        "STOPPT …": "STOPPING …",
        "KEINE AUFNAHME": "NO CAPTURE",
        "Strg/⌘ + Klick: Mehrfachauswahl · Ziehen · Pfeiltasten": "Ctrl/⌘ + click: multi-select · drag · arrow keys",
        "Zonen": "zones",
        "Testkanal": "Test channel",
        "Prozent": "percent",

        "Bildschirmfarben empfangen": "Screen colors received",
        "01 / Zonen-Editor": "01 / Zone editor",
        "LIVE-VORSCHAU · 5 HZ": "LIVE PREVIEW · 5 HZ",
        "Segmentfarben": "Segment colors",
        "BILDRATE": "FRAME RATE",
        "VERARBEITUNG": "PROCESSING",
        "AKTIVE ZONEN": "ACTIVE ZONES",
        "gesamt": "total",
        "Bildrand": "Screen edge",
        "Systemaudio empfangen": "System audio received",
        "Hexagon / Kanal-Labor": "Hexagon / Channel lab",
        "Bildschirmzonen": "Screen zones",

        "Szenen": "Scenes",
        "Musik": "Music",
        "Licht": "Lights",
        "Stoppen": "Stop",
        "Abbrechen": "Cancel",
        "Vorschau": "Preview",
        "Licht starten": "Start lights",
        "Sync starten": "Start sync",
        "Einstellungen öffnen": "Open settings",
        "Effekt auswählen": "Choose an effect",
        "Geräte suchen": "Find devices",
        "Suche läuft …": "Searching …",
        "Dein Setup": "Your setup",
        "Suche deine Leuchten …": "Looking for your lights …",
        "Noch keine Leuchten gefunden": "No lights found yet",
        "LAN-Steuerung in Govee Home aktivieren. Mac und Leuchten brauchen dasselbe Netzwerk.": "Enable LAN Control in Govee Home. Your Mac and lights must share a reachable network.",
        "Profilname": "Profile name",
        "Aktuelles Setup als Profil speichern": "Save current setup as a profile",
        "Noch keine gespeicherten Profile": "No saved profiles yet",
        "Profil laden": "Load profile",
        "Änderungen werden automatisch gesichert.": "Changes are saved automatically.",
        "Profile": "Profiles",
        "Speichern": "Save",
        "Bereit für dein Licht.": "Ready for your lights.",
        "Mein Setup": "My setup",
        "Lokal auf deinem Mac": "Local on your Mac",
        "Govee-Geräteeffekt": "Govee device effect",
        "LOKAL · BEREIT": "LOCAL · READY",
        "NUR VORSCHAU": "PREVIEW ONLY",
        "MODUSWECHSEL …": "SWITCHING MODE …",
        "RAUM-MIX LÄUFT": "ROOM MIX RUNNING",
        "GOVEE · BESTÄTIGT": "GOVEE · CONFIRMED",
        "SYNC LÄUFT": "SYNC RUNNING",
        "LICHT LÄUFT": "LIGHTS RUNNING",
        "Desktop / Lichtlabor": "Desktop / Light lab",
        "Dein Bildschirm.\nEin ganzer Raum.": "Your screen.\nAn entire room.",
        "Dein Sound.\nDein Licht.": "Your sound.\nYour lights.",
        "Originale.\nNeue Eskalation.": "Original effects.\nRoom-wide expression.",
        ".\nLicht mit Charakter.": ".\nLight with character.",
        "Farben direkt vom Desktop. Dein Mapping wartet im Setup.": "Colors straight from your desktop. Your mapping lives in Setup.",
        "Reaktion und Farben direkt auf deine Musik abstimmen.": "Tune reactions and colors to your music.",
        "Die Govee-Bibliothek für deine Geräte.": "The Govee library for your devices.",
        "AUDIO → LICHT": "AUDIO → LIGHT",
        "LOKALE LICHTSZENEN": "LOCAL LIGHT SCENES",
        "Govee-Effekt · Befehl bestätigt": "Govee effect · command confirmed",
        " · Die Animation wird vom Gerät dargestellt. Keine Live-Vorschau verfügbar.": " · The animation runs on the device. No live preview available.",
        "Auf ": "On ",
        "Musikquelle": "Music source",
        "Mac · Systemaudio": "Mac · System audio",
        "Govee · Geräte-Musik": "Govee · Device music",
        "Szenenquelle": "Scene source",
        "Studio · Lokal": "Studio · Local",
        "Wähle deinen Zustand": "Choose your atmosphere",
        "LIVE WECHSELBAR": "SWITCH LIVE",
        "Dein Mapping bleibt dein Mapping.": "Your mapping stays yours.",
        "Zonen verschieben, Geräte zuordnen und kalibrieren: alles im Setup-Tab.": "Move zones, assign devices and calibrate them in the Setup tab.",
        "Setup öffnen": "Open Setup",
        "Govee / Geräte-Effekte": "Govee / Device effects",
        "Der Effekt übernimmt.": "Let the effect take over.",
        "Original- und DIY-Effekte besitzen ihre eigenen Farben und Abläufe. Unsere Regler für Musik und lokale Szenen wirken hier nicht.": "Original and DIY effects have their own colors and timing. Local scene and music controls do not apply here.",
        "Pro Leuchte übernimmt genau eine Quelle. Im Raum-Mix können Govee-Gerätemusik und Ambilight auf verschiedenen Leuchten gleichzeitig laufen. Änderungen in der Zuordnung werden beim Start übernommen.": "Each light has one source. Room mix runs Govee music and Ambilight on different lights. Apply assignment changes by starting the room again.",
        "Regiepult": "Control desk",
        "Du hast den Regler.": "Make it yours.",
        "Der Bass darf rein.": "Let the bass in.",
        "Mac-Systemaudio · kein Mikrofon. Bass, Mitten und Höhen treiben unterschiedliche Kanäle.": "Mac system audio · no microphone. Bass, mids and highs drive different channels.",
        "Lokale Ausgabe auf deinem gesamten aktivierten Setup.": "Local output across your enabled lights.",
        "Master-Helligkeit": "Master brightness",
        "Hintergrund": "Background",
        "Farbe": "Color",
        "Zum Wechsel der Hintergrundquelle kurz stoppen.": "Stop briefly to change the background source.",
        "Ambilight / Hintergrund": "Ambilight / Background",
        "Warte auf Bildschirmfarben": "Waiting for screen colors",
        "Ambilight-Helligkeit": "Ambilight brightness",
        "Ambilight-Sättigung": "Ambilight saturation",
        "Ambilight-Glättung": "Ambilight smoothing",
        "Filmbalken ausblenden": "Ignore black bars",
        "Bildschirm und Zonen aus Setup. Musik und Hintergrund werden separat geglättet.": "Display and zones come from Setup. Music and background are smoothed independently.",
        "Grundhelligkeit": "Base brightness",
        "Hintergrundfarbe": "Background color",
        "Effektintensität": "Effect intensity",
        "Bewegung": "Movement",
        "Schweiflänge": "Trail length",
        "Effektrichtung umkehren": "Reverse effect direction",
        "Bewegung folgt der Kanalfolge pro Gerät.": "Movement follows each device's channel order.",
        "Musik-Sättigung": "Music saturation",
        "Empfindlichkeit": "Sensitivity",
        "Nachglühen": "Decay",
        "Bei Stille läuft Ambilight weiter. Musik liegt darüber; Master und Gerätehelligkeit begrenzen die Gesamtausgabe.": "Ambilight continues during silence. Music is layered on top; master and device brightness limit the output.",
        "Bei Stille bleibt nur dein Grundlicht. Die Vorschau hört ebenfalls Systemaudio, sendet aber nichts an die Leuchten.": "Only the base light remains during silence. Preview also listens to system audio, without sending to lights.",
        "Verbunden": "Connected",
        "AN": "ON",
        "AUS": "OFF",
        "Stoppen setzt die gespeicherten Grundwerte deiner Leuchten zurück.": "Stop restores your lights' saved basic settings.",
        "Audio / Reaktion": "Audio / Reaction",
        "LIVE EINSTELLBAR": "ADJUST LIVE",
        "Mac-Reaktionen laufen über Panel- und Strip-Kanäle. Einzelne Hexagon-Teilflächen sind hier noch nicht frei adressierbar.": "Mac reactions use panel and strip channels. Individual Hexagon sub-faces are not freely addressable here.",
        "Musikfarben": "Music colors",
        "Farbverhalten": "Color behavior",
        "Satte Farben aktivieren": "Enable vivid colors",
        "Warte auf Systemaudio": "Waiting for system audio",
        "SYSTEMAUDIO EMPFANGEN": "SYSTEM AUDIO RECEIVED",
        "MITTEN": "MIDS",
        "HÖHEN": "HIGHS",
        "Berechnete Farben / keine Lichtausgabe": "Computed colors / no light output",
        "Ausgabefarben / Kanalvorschau": "Output colors / channel preview",
        "Look-Vorschau / keine Lichtausgabe": "Look preview / no light output",
        "Dein Licht wartet im Setup.": "Your lights are waiting in Setup.",
        "Flächen & Linien erkunden": "Explore faces and lines",
        "Experimentelle Kanalzahl für Szenen und Musik. Die Zuordnung zu Teilflächen ist noch nicht bestätigt; mehr Kanäle bedeuten nicht automatisch mehr adressierbare LEDs.": "Experimental channel count for scenes and music. Sub-face mapping is unverified; more channels do not necessarily mean more addressable LEDs.",
        "Show-Kanäle": "Show channels",
        "Kanal 1,5 Sekunden markieren": "Highlight channel for 1.5 seconds",
        "Türkis auf dunklem Grund, danach Wiederherstellung. Ambilight-Zonen bleiben unverändert.": "Cyan on a dark background, then restore. Ambilight zones stay unchanged.",
        "Show-Kanalzahl zurücksetzen": "Reset show channel count",
        "Govees Spielzeugkiste.": "Govee's effect library.",
        "Originaleffekte für den ganzen Raum oder einzelne Geräte.": "Original effects for your whole room or individual devices.",
        "Katalog aktualisieren": "Refresh catalog",
        "Lädt …": "Loading …",
        "Ganzer Raum · Original": "Whole room · Original",
        "Einzelgerät · Original & DIY": "Single device · Original & DIY",
        "Gerät": "Device",
        "Effekte": "Effects",
        "Alle": "All",
        "Effekte suchen …": "Search effects …",
        "Govee-Effekte suchen": "Search Govee effects",
        "Stand": "Updated",
        "Abruf unvollständig": "Refresh incomplete",
        "Gerät im Setup aktivieren, um Effekte zu starten.": "Enable this device in Setup to start effects.",
        "Key eingeben und den Katalog laden. Deine lokalen Szenen bleiben jederzeit verfügbar.": "Enter a key and load the catalog. Local scenes remain available at any time.",
        "Keine passenden Effekte. Bei leerem DIY-Katalog zuerst einen Look in Govee Home speichern und aktualisieren.": "No matching effects. If DIY is empty, save a look in Govee Home and refresh.",
        "Govee bestätigt": "Govee confirmed",
        "Auf Gerät starten": "Start on device",
        "auf ausgewähltem Gerät starten": "start on selected device",
        "Katalog offline gespeichert · Start über Govee-Cloud · keine Bildschirm- oder Audiodaten übertragen. Stoppen stellt die gesicherten Grundwerte wieder her; ein vorheriger Govee-Effekt lässt sich daraus nicht rekonstruieren.": "Catalog cached offline · starts via Govee cloud · no screen or audio upload. Stop restores saved basic settings, not a previous vendor animation.",
        "Je Gerät ein Originaleffekt. Alle aktivierten Leuchten starten gemeinsam; die Govee-Befehle werden nacheinander gesendet.": "Choose an original effect per device. Start all enabled lights together; Govee commands are sent sequentially.",
        "Szene auswählen …": "Choose a scene …",
        "Originalszene": "Original scene",
        "Originalszene für": "Original scene for",
        "Für dieses Gerät zuerst den Katalog aktualisieren.": "Refresh the catalog for this device first.",
        "Originalszenen auf allen Geräten starten": "Start original scenes on all devices",
        "Alle Geräte brauchen eine Auswahl. Modellspezifische Effekte bleiben beim passenden Gerät; es werden keine fremden Szenen-IDs übertragen.": "Choose a scene for every device. Model-specific effects stay with the matching device; IDs are never copied across models.",
        "Variante": "Variant",
        "Key im macOS-Schlüsselbund": "Key in macOS Keychain",
        "Govee-Verbindung": "Govee connection",
        "Schließen": "Close",
        "Key ändern": "Change key",
        "Dauerhaft speichern": "Save permanently",
        "Govee API-Key": "Govee API key",
        "Govee-Musik": "Govee music",
        "Ambilight": "Ambilight",
        "Nicht verwenden": "Do not use",
        "Govee-Automatik": "Govee automatic",
        "Eigene Farbe": "Custom color",
        "Glut": "Ember",
        "Der ganze Raum spielt mit.": "The whole room joins in.",
        "Govee-Musik auf allen Leuchten – oder Hexagon-Musik mit Ambilight auf den Strips. Jede Leuchte bekommt genau eine Quelle; Musik und Bildschirmfarben werden nicht auf demselben Gerät überlagert.": "Govee music on every light, or Hexagon music with Ambilight on strips. Each light has one source; music and screen colors are not layered on the same device.",
        "Musikmodi abrufen": "Fetch music modes",
        "Ganzer Raum · Musik": "Whole room · Music",
        "Hexagon-Musik + Strip-Ambilight": "Hexagon music + strip Ambilight",
        "Quelle für": "Source for",
        "Musikmodus für": "Music mode for",
        "Musikmodi zuerst abrufen": "Fetch music modes first",
        "Bildschirm & Mapping aus Setup": "Display and mapping from Setup",
        "Raum-Musik starten": "Start room music",
        "Zuordnung mit Raum-Musik starten übernehmen; Farben und Regler rechts lassen sich während der Ausgabe anwenden. Govee reagiert im Geräte-Modus; nur zugeordnete Ambilight-Leuchten erhalten Mac-Bildschirmfarben. Keine Mac-Audioübertragung an Govee. Stoppen stellt alle gesicherten Grundwerte wieder her.": "Apply assignments with Start room music; adjust colors and controls during output. Govee reacts at the device; only Ambilight lights receive screen colors. No Mac audio is sent to Govee. Stop restores saved basic settings.",
        "Govee-Gerätemusik / Effekte": "Govee device music / Effects",
        "Raum-Mix · getrennte Ausgabe pro Leuchte": "Room mix · separate output per light",
        "Warte auf Bildschirm": "Waiting for display",
        "Govee-Animationen werden am Gerät dargestellt. Farbvorschau nur für Ambilight.": "Govee animations run on the device. Color preview is available only for Ambilight.",
        "Raum / Regiepult": "Room / Control desk",
        "Dein Raum. Dein Pegel.": "Your room. Your level.",
        "Musik-Helligkeit": "Music brightness",
        "Gerätewerte": "Device settings",
        "Lichtintensität der Govee-Musikgeräte. Kein zusätzliches Grundlicht in Musikpausen.": "Brightness of Govee music devices. No additional base light during silence.",
        "Musik-Empfindlichkeit": "Music sensitivity",
        "Farbschema": "Color scheme",
        "Raum-Farbschema": "Room color scheme",
        "Govee bestimmt die Farben seiner internen Animation.": "Govee chooses the colors of its internal animation.",
        "Eine feste Farbe je Musikgerät, als abgestimmtes Schema im Raum verteilt. Die Animation bleibt beim Gerät.": "One fixed color per music device, coordinated across the room. The animation runs on each device.",
        "Eigene Musikfarbe": "Custom music color",
        "Ambilight / Grundlicht": "Ambilight / Base light",
        "Helligkeit": "Brightness",
        "Sättigung": "Saturation",
        "Glättung": "Smoothing",
        "Nur für die als Ambilight zugeordneten Leuchten.": "Only applies to lights assigned to Ambilight.",
        "Wird übernommen …": "Applying …",
        "Regler übernehmen": "Apply controls",
        "Während der Ausgabe ohne kompletten Neustart. Neue Gerätezuordnung: Raum-Musik starten.": "Apply during output without restarting the room. For assignment changes, start room music again.",
        "Geschwindigkeit und Nachleuchten steuert der Govee-Modus selbst. Separate Regler dafür oder für ein Musik-Mindestlicht bietet diese API nicht.": "Speed and decay are controlled by the Govee mode. This API exposes no separate controls for them or minimum music brightness.",
        "Licht folgt deinem Bildschirm.": "Light follows your screen.",
        "Zieh jedes Segment dorthin, wo es seine Farbe aufnehmen soll.": "Drag each segment to the screen area it should sample.",
        "ANORDNEN": "ARRANGE",
        "START FÜR LIVE-FARBEN": "START FOR LIVE COLORS",
        "Dein Bildschirm wird zur Lichtquelle.": "Your display becomes a light source.",
        "Vorschau starten, um Farben live zu sehen.": "Start preview to see live colors.",
        "Bildschirm": "Display",
        "02 / Feinabstimmung": "02 / Fine tuning",
        "Vorherige Sitzung": "Previous session",
        "Gesicherte Lichtwerte sind noch vorhanden.": "Saved light settings are still available.",
        "Lichtwerte wiederherstellen": "Restore light settings",
        "Gerätename": "Device name",
        "Im Sync verwenden": "Include in sync",
        "Segmente": "Segments",
        "Startwert · Anzahl und Reihenfolge am Gerät prüfen.": "Starting value · verify count and order on the device.",
        "Reihenfolge umkehren": "Reverse order",
        "Ausgabe": "Output",
        "Protokoll": "Protocol",
        "Auf Gerät strecken": "Stretch on device",
        "Zuordnung geprüft": "Mapping verified",
        "DreamView nutzt ein nicht öffentlich dokumentiertes Protokoll. Einzelfarbe ist der einfachere LAN-Modus.": "DreamView uses an undocumented protocol. Single color is the simpler LAN mode.",
        "Geräteoptionen": "Device options",
        "Breite": "Width",
        "Höhe": "Height",
        "Test läuft …": "Test running …",
        "Segment kurz testen": "Test segment briefly",
        "Leuchtet kurz türkis. Danach werden die vorherigen Grundwerte zurückgesendet.": "Briefly lights cyan, then restores the previous basic settings.",
        "Gesamtes Setup": "Entire setup",
        "Weiche Übergänge": "Smooth transitions",
        "Farbupdates": "Color updates",
        "Schwarze Filmbalken erkennen": "Detect black bars",
        "Beim Stoppen: Grundfarbe, Helligkeit und Ein/Aus zurücksetzen. Govee-Szenen können nicht rekonstruiert werden.": "On stop: restore base color, brightness and power. Vendor scenes cannot be reconstructed.",
        "Setup-Ordner öffnen": "Open setup folder",
        "Fläche": "Grid",
        "Einzelfarbe": "Single color",
        "Automatisch": "Automatic",
        "Oben": "Top",
        "Unten": "Bottom",
        "Links": "Left",
        "Rechts": "Right",
        "Rahmen": "Border",
        "Spektrum": "Spectrum",
        "Bass-Puls": "Bass pulse",
        "Basswelle": "Bass wave",
        "Feuer": "Fire",
        "Eis": "Ice",
        "Bandfarben": "Band colors",
        "Farbfluss": "Color drift",
        "Impulswechsel": "Onset shift",
        "Klare Farbgruppen wandern wie ein leuchtendes Prisma.": "Distinct color groups drift like a glowing prism.",
        "Gegenläufige Lichtlinien und dunkle Zwischenräume.": "Counter-moving light lines with dark gaps.",
        "Schillernde Farbbänder. Flüssig, tief und langsam.": "Iridescent color bands. Fluid, deep and slow.",
        "Leuchtköpfe mit langen Schweifen durch die Kanalfolge.": "Light heads with long trails move through the channels.",
        "Bassimpulse ziehen von außen zur Mitte.": "Bass impulses travel from the edges to the center.",
        "Cyan trifft Magenta. Feierabend im Cyberkeller.": "Cyan meets magenta. After hours in the cyber basement.",
        "Fließende Polarlichter. Nervensystem auf Urlaub.": "Flowing northern lights. A holiday for your nervous system.",
        "Violette Umlaufbahnen um einen dunklen Kern.": "Violet orbits around a dark core.",
        "Glühende Kohlen. Langsam, warm, verdammt gemütlich.": "Glowing embers. Slow, warm and seriously cozy.",
        "Warmes Grundlicht. Der Kopf darf arbeiten.": "Warm base light. Give your mind room to work.",
        "Bass im Fundament. Höhen ziehen Leuchtspuren.": "Bass lays the foundation. Highs leave light trails.",
        "Drei Farbgruppen springen auf Impulse; Bass, Mitten und Höhen bleiben getrennt.": "Three color groups jump on impulses; bass, mids and highs stay separate.",
        "Bass wächst von der Mitte nach außen; Höhen antworten vom Rand.": "Bass grows outward from the center; highs answer from the edges.",
        "Höhen setzen kurze Lichtpunkte, darunter rollen dunkle Basswolken.": "Highs spark brief highlights above rolling bass clouds.",
        "Weiche Farbbänder verformen sich mit Mitten und Bass.": "Soft color bands bend with mids and bass.",
        "Bass, Mitten und Höhen verteilen sich auf die Kanäle.": "Bass, mids and highs spread across the channels.",
        "Das ganze Setup atmet mit dem Bass.": "The whole setup breathes with the bass.",
        "Laufende Lichtköpfe reagieren auf die Musikenergie.": "Moving light heads respond to musical energy.",
        "Bassanstiege starten eine wandernde Welle.": "Rising bass launches a traveling wave.",
        "Geräte im lokalen Netzwerk.": "devices on the local network.",
        "Gerätesuche per Multicast nicht erreichbar · bekannte Leuchten werden direkt geprüft.": "Multicast discovery unavailable · probing known lights directly.",
        "Show-Einstellungen konnten nicht gespeichert werden:": "Could not save show settings:",
        "Setup konnte nicht gespeichert werden:": "Could not save setup:",
        "Unbekanntes Profilformat.": "Unknown profile format.",
        "Gespeichertes Setup konnte nicht gelesen werden:": "Could not read saved setup:",
        "Vorherige Lichtwerte werden wiederhergestellt …": "Restoring previous light settings …",
        "Eine Leuchte bestätigt die Wiederherstellung noch nicht. Prüfe ihre Verbindung und starte den Sync erneut; die App versucht es automatisch noch einmal.": "A light has not confirmed restoration. Check its connection and start sync again to retry automatically.",
        "Erlaube Govee Studio unter Systemeinstellungen → Datenschutz & Sicherheit → Bildschirmaufnahme. Danach die App gegebenenfalls neu öffnen.": "Allow Govee Studio in System Settings → Privacy & Security → Screen Recording. Then reopen the app if needed.",
        "Der gewählte Bildschirm ist nicht verfügbar.": "The selected display is unavailable.",
        "Wähle mindestens eine Leuchte aus.": "Select at least one light.",
        "aktiv · Farben werden lokal gesendet.": "active · sending colors locally.",
        "Vorschau · Leuchten bleiben unverändert.": "Preview · lights remain unchanged.",
        "Bitte einen Govee-API-Key eingeben oder aus dem Schlüsselbund laden.": "Enter a Govee API key or load it from Keychain.",
        "Dieses Gerät zuerst im Setup aktivieren.": "Enable this device in Setup first.",
        "Bitte Govee-API-Key eingeben.": "Enter a Govee API key.",
        "Vorherige Lichtwerte konnten noch nicht wiederhergestellt werden.": "Previous light settings could not be restored yet.",
        "Für Ambilight bitte Bildschirmaufnahme erlauben.": "Allow screen recording for Ambilight.",
        "Gewählter Bildschirm nicht verfügbar.": "Selected display unavailable.",
        "Gerät(e)": "device(s)",
        "Ambilight-Gerät(e)": "Ambilight device(s)",
        "Darstellung am Gerät prüfen.": "Check the effect on the device.",
        "Regler übernommen · Gerätezuordnung unverändert.": "Controls applied · device assignments unchanged.",
        "Gestoppt · Wiederherstellung noch offen; beim nächsten Sync-Start wird sie erneut versucht.": "Stopped · restoration pending; the next sync start will retry.",
        "Gestoppt · vorherige Lichtwerte zurückgesendet.": "Stopped · previous light settings sent back.",
        "Vorschau beendet · Leuchten unverändert.": "Preview ended · lights unchanged.",
        "Lichtwerte noch nicht bestätigt.": "Light settings not yet confirmed.",
        "Wiederherstellung noch offen · Verbindung der Leuchten prüfen.": "Restoration pending · check device connections.",
        "Vorherige Lichtwerte wiederhergestellt · bereit für Sync.": "Previous light settings restored · ready to sync.",
        "Eine Leuchte bestätigt die Lichtwerte noch nicht. Bitte ihre LAN-Verbindung prüfen und erneut versuchen.": "A light has not confirmed its settings. Check its LAN connection and try again.",
        "Bitte zuerst die Lichtwerte der vorherigen Sitzung wiederherstellen.": "Restore the previous session's light settings first.",
        "Sichtbare Zuordnung bitte am Gerät prüfen.": "Verify the visible mapping on the device.",
        "Test gesendet · Kanal": "Test sent · channel",
        "Geräte-Musik": "Device music",
        "Ungültige Govee-Geräteantwort; gespeicherte Auswahl bleibt erhalten.": "Invalid Govee device response; saved selection retained.",
        "Bitte einen gültigen Govee-API-Key eingeben.": "Enter a valid Govee API key.",
        "Keine gültige Govee-Antwort.": "No valid Govee response.",
        "Bei 401/403 Key prüfen; bei 429 später erneut versuchen.": "For 401/403 check the key; for 429 retry later.",
        "Musikfähigkeiten konnten nicht abgerufen werden. Key und Verbindung prüfen.": "Could not fetch music capabilities. Check the key and connection.",
        "Modi pro Gerät · Änderungen werden beim Start übernommen.": "Modes per device · changes apply on start.",
        "Dauerhaft speichern: künftig ohne erneute Eingabe.": "Save permanently to skip future key entry.",
        "Katalog lokal verfügbar. Zum Aktualisieren oder Starten wird Internet benötigt.": "Catalog available locally. Refreshing or starting requires internet.",
        "Automatisch geladen · bleibt nach App-Neustart verfügbar.": "Loaded automatically · available after app restart.",
        "Raum-Auswahl konnte nicht gespeichert werden:": "Could not save room selection:",
        "Bitte einen gültigen Key eingeben.": "Enter a valid key.",
        "Dauerhaft im macOS-Schlüsselbund gespeichert.": "Saved permanently in macOS Keychain.",
        "Key aus dem Schlüsselbund entfernt.": "Key removed from Keychain.",
        "Raumkonfiguration nicht gespeichert:": "Room configuration not saved:",
        "Musikmodi für": "Music modes for",
        "Geräte lokal gespeichert.": "devices saved locally.",
        "Lade Original & DIY für": "Loading Original & DIY for",
        "Einträge lokal gespeichert": "entries cached locally",
        "Geräte mit Abruffehlern.": "devices with refresh errors.",
        "Katalog geladen, aber nicht gespeichert:": "Catalog loaded but not saved:",
        "Govee liefert keine gültigen Musikfähigkeiten.": "Govee returned invalid music capabilities.",
        "zuerst abrufen oder Gerät anders zuordnen.": "fetch first or assign another source.",
        "Gerätezuordnung geändert. Bitte Raum-Musik neu starten.": "Device assignments changed. Start room music again.",
        "Mindestens ein Musikgerät wählen. Jedes Gerät darf nur eine Ausgabequelle haben.": "Select at least one output device. Each device must have only one source.",
        "Ein gewähltes Musikgerät ist nicht mehr aktiviert.": "A selected output device is no longer enabled.",
        "Ein Ambilight-Gerät ist nicht mehr aktiviert.": "An Ambilight device is no longer enabled.",
        "Schlüsselbund-Fehler": "Keychain error",
        "Der Key wurde nicht in einer Datei gespeichert.": "The key was not saved to a file.",
        "Gespeicherter API-Key konnte nicht gelesen werden.": "Could not read the saved API key.",
        "UDP-Socket konnte nicht geöffnet werden.": "Could not open UDP socket.",
        "UDP-Port 4002 ist nicht verfügbar": "UDP port 4002 is unavailable",
        "Andere Govee-Apps bitte schließen und erneut suchen.": "Close other Govee apps and search again.",
        "LAN-Verbindung ist geschlossen.": "LAN connection is closed.",
        "Ungültige Geräteadresse:": "Invalid device address:",
        "UDP-Ausgabe an": "UDP output to",
        "fehlgeschlagen:": "failed:",
        "antwortet nicht auf die Statusabfrage. Die Ausgabe wurde nicht gestartet.": "did not respond to the status request. Output was not started.",
        "Govee meldet Fehler": "Govee reported error",
        "Bildschirm-Sync beendet:": "Screen sync stopped:",
        "Aktuell": "Currently",
        "Sättigung – Farben sind fast weiß.": "saturation — colors are nearly white.",
        " auswählen.": " must be selected.",
    ]
    private static let replacements: [(String,String)] = english.sorted { $0.key.count > $1.key.count }
    private static let cache: NSCache<NSString,NSString> = { let value=NSCache<NSString,NSString>();value.countLimit=2048;return value }()
    // Replace source spans once, never recursively translate the English result.
    static func translate(_ value:String,to language:AppLanguage) -> String {
        guard language == .en else { return value }
        if let exact=english[value] { return exact }
        if let cached=cache.object(forKey:value as NSString) { return cached as String }
        if let exact=english.first(where:{$0.key.uppercased() == value}) { return exact.value.uppercased() }
        var output="", index=value.startIndex
        while index < value.endIndex {
            var matched=false
            for (source,target) in replacements where value[index...].hasPrefix(source) {
                let end=value.index(index,offsetBy:source.count)
                let leftOK = !source.first!.isLetter || index == value.startIndex || !value[value.index(before:index)].isLetter
                let rightOK = !source.last!.isLetter || end == value.endIndex || !value[end].isLetter
                if leftOK && rightOK { output += target;index=end;matched=true;break }
            }
            if !matched { output.append(value[index]);index=value.index(after:index) }
        }
        cache.setObject(output as NSString,forKey:value as NSString)
        return output
    }
}
